import type { Metadata } from "next";
import { Wix_Madefor_Text } from "next/font/google";
import "@/app/globals.css";

const madefor = Wix_Madefor_Text({
  weight: ["400", "500", "700", "800"],
  variable: "--font-madefor",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jadetimes Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${madefor.variable} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
